services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"  # Porta padrão exposta
    command: ["mongod", "--bind_ip_all", "--auth", "false"]
    # O "--auth false" é para não exigir autenticação (modo inseguro)

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 6050:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
